#    _   __           ____       __                __
#   / | / /__  __  __/ __ \___  / /___  ____ _____/ /__  _____
#  /  |/ / _ \/ / / / /_/ / _ \/ / __ \/ __ `/ __  / _ \/ ___/
# / /|  /  __/ /_/ / _, _/  __/ / /_/ / /_/ / /_/ /  __/ /
#/_/ |_/\___/\__, /_/ |_|\___/_/\____/\__,_/\__,_/\___/_/
#           /____/

time: 10 #время в секундах через которая будет перезагрузка

commands_list: #команды, которые выполнятся от имени консоли после таймера
  commands:
    - "save-all"
    - "stop"